version: '3.9'
services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - .:/usr/share/nginx/html
        networks:
            network1:
                ipv4_address: 192.168.105.10

    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            network1:
                ipv4_address: 192.168.105.20

    mysql:
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        ports:
            - ${DB_PORT:-3306}:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - TZ=Asia/Tokyo
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            network1:
                ipv4_address: 192.168.105.30

    mysql-testing:
        build:
            context: .
            dockerfile: ./docker/mysql/Dockerfile
        ports:
            - ${DB_TESTING_PORT:-13306}:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - TZ=Asia/Tokyo
        volumes:
            - mysql-testing-data:/var/lib/mysql
        networks:
            network1:
                ipv4_address: 192.168.105.31

networks:
    network1:
        ipam:
            driver: default
            config:
                - subnet: 192.168.105.0/24

volumes:
    mysql-data:
        driver: local
    mysql-testing-data:
        driver: local
